#imagem usada do docker hub
FROM tomcat:latest
#informações de quem criou
MAINTAINER Humberto Moura <humbertomoura.n@gmail.com>
#adicionar no container o seguinte o seguinte arquivo no seguinte diretório
ADD /sample/ /webapps/
#usar a porta 80
EXPOSE 8080

