#imagem usada do docker hub
FROM httpd:latest
#informações de quem criou
MAINTAINER Humberto Moura <humbertomoura.n@gmail.com>
#adicionar no container o seguinte o seguinte arquivo no seguinte diretório
#ADD index.html /usr/share/nginx/html
ADD index.html /usr/local/apache2/htdocs
#usar a porta 80
EXPOSE 80

